[package]
name = "jarsdraw-demo"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.114"
jarsdraw = { version = "0.1.0", path = "../jarsdraw" }
web-sys = { version = "0.3.91", features = [
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "Node",
    "Window",
    "console",
] }
